### ISSUE TITLE
Add paging to "get features with radius search"

### ISSUE THREAD

**Issue by deeplook** [heremaps/xyz-hub#266]
This would be really helpful as users would not need to write their own solutions to what appears to be a standard best practice for RESTful APIs, see https://www.moesif.com/blog/technical/api-design/REST-API-Design-Filtering-Sorting-and-Pagination/.

https://xyz.api.here.com/hub/static/swagger/#/Read%20Features/getFeaturesBySpatial

**Comment by jwegne** [comment]
Thank you for your suggestion. Enhanced iteration over data is something we are consideration for a future release.

**Comment by burritojustice** [comment]
Thanks for your feedback -- we continue to evaluate the best approaches to this and will reopen this when we have more specifics to share.
