### ISSUE TITLE
Providing binary releases?

### ISSUE THREAD

**Issue by deeplook** [heremaps/xyz-hub#29]
Are there any binary releases available? This would reduce the compile time quite a bit, which is nice for building hosted online environments more quickly.

**Comment by lceni** [comment]
Hello @deeplook, unfortunately not yet.
We're planning to add them into the Releases, but some work is needed yet.
Thank you for the suggestion.

**Comment by lceni** [comment]
Reopening this issue keep track.

**Comment by roegi** [comment]
Done by https://github.com/heremaps/xyz-hub/pull/506
