### ISSUE TITLE
Testing Spatial search can lead to incorrect results

### ISSUE THREAD

**Issue by cfjedimaster** [heremaps/xyz-hub#292]
I was using the spatial search function here (https://xyz.api.here.com/hub/static/swagger/#/Read%20Features/getFeaturesBySpatial) and noticed I wasn't getting results when I should have. The reason I didn't is because the 'default' text for params included this code:

```
OrderedMap { "p.myProperty": "someValue", "p.otherProperty": 5 }
```

Other fields on the form have descriptive text for the field but they do NOT actually get sent to the API. So for example:

![image](https://user-images.githubusercontent.com/393660/92634772-6c0e8e00-f29a-11ea-9bf4-6b067d9df1cb.png)

Even though you see text in limit, it's not actually passed to the API. 

To fix this, we need to remove the text from the textarea so it doesn't get passed when a user doesn't notice that it is "real" text.

**Comment by haifeng2013** [comment]
@cfjedimaster Thanks for your feedback.
We don't need to change the API specification as this is because of an issue in current version of Swagger UI. I will update the Swagger UI to latest version and this issue should be solved.

**Comment by haifeng2013** [comment]
Close this issue as Swagger UI is not part of this Repo.
