### ISSUE TITLE
Documentation fix - Getting started : git clone; cd xyz-hub; ...

### ISSUE THREAD

**Issue by sylvaingaudan** [heremaps/xyz-hub#387]
In section [Getting started](https://github.com/heremaps/xyz-hub#getting-started), the shell commands should be

```sh
git clone https://github.com/heremaps/xyz-hub.git
cd xyz-hub
mvn clean install
```

**Comment by roegi** [comment]
Hi @sylvaingaudan, thanks for reporting it. README has been fixed.
