### ISSUE TITLE
Please add support for `GeometryCollection`s to the HERE XYZ Hub

### ISSUE THREAD

**Issue by rdesgroppes** [heremaps/xyz-hub#596]
Currently, loading GeoJSON content with (standard) [GeometryCollection](https://datatracker.ietf.org/doc/html/rfc7946#section-3.1.8)s leads https://geojson.tools to report errors s.a. `1 feature(s) added successfully and 1 feature(s) failed to load`, without rendering said `GeometryCollection`s.

Although the limitation is documented ([GeometryCollection is not supported by HERE XYZ Hub. It is just included here for completeness.](https://www.here.xyz/viewer-tool/geojsonbasics/#geometrycollection)), it forces us to resort to other web applications (s.a. https://geojson.io) to get rendering - thus without HERE maps.

Could you therefore please consider supporting `GeometryCollection`s?

**Comment by goshev** [comment]
Hi @rdesgroppes,

Are you requesting to add support for visualizing GeometryCollection in https://geojson.tools or storing them in XYZ Hub?

**Comment by rdesgroppes** [comment]
Hi @goshev! Being able to visualize `GeometryCollection`s from within https://geojson.tools would be enough to address my team's need.

**Comment by goshev** [comment]
Thanks for clarifying @rdesgroppes! https://geojson.tools is a separate project that's not part of XYZ Hub. However, I forwarded your request.

**Comment by hmorch** [comment]
Hi @rdesgroppes,

thank you for your suggestion. We will look into this, but I can't promise if or when this will be available.

**Comment by rdesgroppes** [comment]
Thanks, @hmorch. Will keep using https://geojson.io/ until then.
