### ISSUE TITLE
adding swagger documentation

### ISSUE THREAD

**Issue by mapsgeek** [heremaps/xyz-hub#7]
i was expecting to see the local installation of xyz-hub to have the swagger documentation but not sure if it's available and i can't find its end point or still to be upcoming

**Comment by lceni** [comment]
Hello @mapsgeek, thank you for your message.

We do not include swagger-ui as part of xyz-hub,
however, you can run it locally by using:
`docker run -d -p 8081:8080 --rm swaggerapi/swagger-ui`

and then, having an instance of xyz-hub running on localhost:8080,
you can open this link from your browser:
`http://localhost:8081/?url=http://localhost:8080/hub/static/openapi/stable.yaml`

Feel free to comment in case you have any issue.

Lucas Ceni
